App/bbs_foreground/views.py
# -*- coding: utf-8 -*-
# @File    : views.py
# @Theme   ： foreground view
# @Time    : 2020/1/7 18:40
# @Author  : Kalath
import datetime

from flask import Blueprint, render_template, request, redirect, url_for, session, make_response
from flask_login import login_required
from sqlalchemy import func, and_

from App.extensions import db
from App.models import Category, User, Link, Sponsor, Post, Reply
from App.tools import VerifyCode

bbs = Blueprint("bbs", __name__)


@bbs.route("/")
@bbs.route("/<int:cid>/")
def bbs_index(cid=0):
    """

    :param cid: default value is 0, show every section. For other values, show specified section.
    :return:
    """
    # query first level data
    first_layer_category = Category.query.filter(Category.parentid == 0).all()
    # query other levels data
    other_layer_category = Category.query.filter(Category.parentid != 0).all()

    # number of posts
    posts = db.session.query(func.sum(Category.postcount)).group_by(Category.parentid).having(Category.parentid == 0).all()[0][0]
    res = db.session.execute("select sum(replycount) from bbs_category")
    # print(res.fetchall())

    # number of replies
    replies = db.session.query(func.sum(Category.replycount)).group_by(Category.parentid).having(Category.parentid == 0).all()[0][0]
    # number of users
    user_count = User.query.count()
    # name of new user
    new_user = User.query.order_by(-User.id).limit(1).first()
    # all links
    links = Link.query.order_by(-Link.displayorder).all()
    #  sponsor object
    sponsor = Sponsor.query.first()
    # current date
    current_year = datetime.datetime.now().year
    time_now = datetime.datetime.now().strftime("%m-%d %H:%M")

    # last post part
    subcat_nums = len(Category.query.filter(Category.parentid != 0).all())
    subcat_id = [x.cid for x in Category.query.filter(Category.parentid != 0).all()]
    post_s = list()
    for i in range(subcat_nums):
        post_l = Post.query.filter(Post.classid == subcat_id[i]).order_by(-Post.addtime).first()
        post_s.append(post_l)

    # if cid not equal to 0, find the specified section
    if cid != 0:
        for sub_category in first_layer_category:
            if sub_category.cid == cid:
                the_category = sub_category
                break
        return render_template("foreground/index.html", **locals())
    # cid equals to 0, show every section
    else:
        # return render_template("foreground/index1.html", big_category=big_category, cid=cid,
        #                        small_category=small_category)
        return render_template("foreground/index.html", **locals())


@bbs.route("/list/<int:cid>/<int:page>/")
def list_category(cid, page=1):
    #  sponsor object
    sponsor = Sponsor.query.first()
    # current date
    current_year = datetime.datetime.now().year
    time_now = datetime.datetime.now().strftime("%m-%d %H:%M")

    # query to find the specified sub-section
    other_layer = Category.query.filter(Category.cid == cid).all()
    other_layer_name = other_layer[0].classname
    other_layer_parent = other_layer[0].parentid

    # find first-level section according to the sub-section
    first_layer = Category.query.filter(and_(Category.parentid == 0, Category.cid == other_layer_parent)).all()
    first_layer_name = first_layer[0].classname
    first_layer_cid = first_layer[0].cid

    compere_name = other_layer[0].compere
    post_num = other_layer[0].postcount

    classid =cid

    # query first level data
    first_layer_category = Category.query.filter(Category.parentid == 0).all()
    # query other levels data
    other_layer_category = Category.query.filter(Category.parentid != 0).all()

    # Show posts by pagination
    pagenation = Post.query.filter(Post.classid == cid).paginate(page, 10)
    data = {
        # Total number of posts
        'total':pagenation.total,
        # Data list of current page
        'posts': pagenation.items,
        # Current page number
        'current': pagenation.page,
        # Number of posts per page
        'per_page': pagenation.per_page,
        # Total number of pages
        'pages': pagenation.pages,
        # Next page number
        'next': pagenation.next_num,
        # Previous page number
        'pre': pagenation.prev_num
    }
    posts = data["posts"]
    length = len(posts)

    # last reply info
    # authors = db.session.query(User, Post).filter(User.id == Post.authorid).all()
    # print(authors)
    # author_name_dict = dict()
    # for post in posts:
    #     # author_name = db.session.query(User, Post).filter(User.id == Post.authorid).group_by(User.id).having(Post.authorid == post.authorid).order_by(-Post.addtime).limit(1).first()
    #     # if author_name:
    #     #     author_name_dict[author_name.username] = post.authorid
    #     #     print(author_name[1].authorid)
    #     for author in authors:
    #         print(author[0].id)
    #         if author[0].id == post.authorid:
    #             author_name_dict[author.username] = post.authorid
    #             break
    # print(author_name_dict)

    # replies = db.session.query(Reply, Post).filter(Reply.tid == Post.id).all()
    reply_dict = dict()
    # print(replies)
    for post in posts:
        # replies = db.session.query(Reply, Post).filter(Reply.tid == Post.id).group_by(Post.id).having(Post.authorid == post.authorid).order_by(-Reply.addtime).limit(1).first()
        rep = Reply.query.filter(Reply.tid == post.id).order_by(-Reply.addtime).limit(1).first()
        if rep:
            reply_dict[post.id] = list()
            reply_dict[post.id].append(rep.authorid)
            reply_dict[post.id].append(rep.addtime)
        else:
            reply_dict[post.id] = list()

    # print(reply_dict)
    return render_template("foreground/list.html", **locals())


@bbs.route("/publish/<int:cid>/", methods=["GET", "POST"])
# login required to publish a post
@login_required
def publish_post(cid):
    sponsor = Sponsor.query.first()
    # current date
    current_year = datetime.datetime.now().year
    time_now = datetime.datetime.now().strftime("%m-%d %H:%M")

    # query to find the specified sub-section
    other_layer = Category.query.filter(Category.cid == cid).all()
    other_layer_name = other_layer[0].classname
    other_layer_parent = other_layer[0].parentid

    # find first-level section according to the sub-section
    first_layer = Category.query.filter(and_(Category.parentid == 0, Category.cid == other_layer_parent)).all()
    first_layer_name = first_layer[0].classname
    first_layer_cid = first_layer[0].cid

    if request.method == "GET":
        return render_template("foreground/addc.html", **locals())
    else:
        # add a record of the post to the database
        post_title = request.form.get("subject")
        post_content = request.form.get("content")
        post_price = request.form.get("price")
        post = Post()
        post.authorid = session['user_id']
        post.title = post_title
        post.content = post_content
        post.addtime = datetime.datetime.now()
        post.addip = 1122122192
        post.classid = cid
        post.replycount = 0
        post.hits = 0
        post.istop = 0
        post.elite = 0
        post.ishot = 0
        post.rate = post_price
        post.isdel = 0
        post.isdisplay = 0
        db.session.add(post)
        db.session.commit()
        return redirect(url_for("bbs.list_category", cid=cid, page=1))

@bbs.route("/reply/<int:ptid>/<int:cid>/", methods=['POST'])
@login_required
def reply_post(ptid, cid):
    reply = Reply()
    reply.tid = ptid
    reply.authorid = session['user_id']
    reply.content = request.form.get("message")
    reply.addtime = datetime.datetime.now()
    reply.addip = 1122122192
    reply.classid = cid
    reply.isdel = 0
    reply.isdisplay = 0
    db.session.add(reply)
    db.session.commit()
    return redirect(url_for("bbs.list_detail", postid=ptid, page=1))


@bbs.route("/login/")
def bbs_login():
    # query first level data
    first_layer_category = Category.query.filter(Category.parentid == 0).all()
    # query other levels data
    other_layer_category = Category.query.filter(Category.parentid != 0).all()
    # the login page
    sponsor = Sponsor.query.first()
    # current date
    current_year = datetime.datetime.now().year
    time_now = datetime.datetime.now().strftime("%m-%d %H:%M")
    return render_template("foreground/addc-login.html", **locals())


@bbs.route('/notice/')
def login_notice():
    # query first level data
    first_layer_category = Category.query.filter(Category.parentid == 0).all()
    # query other levels data
    other_layer_category = Category.query.filter(Category.parentid != 0).all()
    # the login page
    sponsor = Sponsor.query.first()
    # current date
    current_year = datetime.datetime.now().year
    time_now = datetime.datetime.now().strftime("%m-%d %H:%M")
    message = "Login successfully"
    return render_template("foreground/notice.html", **locals())


@bbs.route('/fail/')
def fail_notice():
    # query first level data
    first_layer_category = Category.query.filter(Category.parentid == 0).all()
    # query other levels data
    other_layer_category = Category.query.filter(Category.parentid != 0).all()
    # the login page
    sponsor = Sponsor.query.first()
    # current date
    current_year = datetime.datetime.now().year
    time_now = datetime.datetime.now().strftime("%m-%d %H:%M")
    message = "Incorrect username or password, please try again "
    return render_template("foreground/notice_fail.html", **locals())


@bbs.route('/deletedpost/<int:ptid>/')
def deleted_post(ptid):
    # query first level data
    first_layer_category = Category.query.filter(Category.parentid == 0).all()
    # query other levels data
    other_layer_category = Category.query.filter(Category.parentid != 0).all()
    # the login page
    sponsor = Sponsor.query.first()
    # current date

App/templates/foreground/addc.html
<!--{include header.html}-->
<!--TOP start-->
<!--{include top.html}-->
<!--TOP end-->

<!--HEAD start-->
<!--{include head.html}-->
<!--HEAD end-->
{% extends "foreground/base.html" %}
{% block content %}
<!--LIST start-->
<div id="wp" class="wp">
	<div id="pt" class="bm cl">
			<div class="z"><a href="../background" class="nvhm" title="{$title}">{$title}</a><em>&raquo;</em><a href="{{ url_for("bbs.bbs_index") }}">Forum</a><em>&raquo;</em><a href="/{{first_layer_cid}}">{{first_layer_name}}</a><em>&raquo;</em><a href="{{url_for('bbs.list_category', cid=cid, page=1) }}">{{other_layer_name}}</a><em>&raquo;</em>Publish a post</div>
	</div>
	<form method="post" autocomplete="off" id="postform" action="">
	<div id="ct" class="ct2_a ct2_a_r wp cl">
		<div class="mn">
			<div class="bm bw0 cl" id="editorbox">
				<ul class="tb cl mbw">
					<li class="a"><a href="javascript:;">Publish a post</a></li>
				</ul>
			
				<div id="postbox">
					<div class="pbt cl">
						<div class="z">
							<span><input type="text" name="subject" id="subject" class="px" onkeyup="showLength(this,'checklen',80);" style="width: 25em" tabindex="1" /></span>
							<span id="subjectchk"><strong id="checklen">80</strong> characters left to be entered</span>
						</div>
					</div>
			
					<div id="e_body_loading">
{#						<script type="text/javascript" src="http://py.codingfans.cc/public/ckeditor/ckeditor.js"></script>#}
                        <script type="text/javascript" src="{{ url_for('static', filename='foreground/ckeditor/ckeditor.js')}}"></script>
						<script type="text/javascript" src="{{ url_for('static', filename='foreground/js/sample.js')}}" ></script>
						<textarea  class="ckeditor"  name="content"  id="editor1"></textarea>
					</div>
				
					<div id="post_extra" class="ptm cl">
						<div id="post_extra_tb" class="cl" onselectstart="return false">
						<label id="extra_price_b" class="a" onclick="showExtra('extra_price')"><span id="extra_price_chk">Price</span></label>
						</div>
					
						<div id="post_extra_c">
							<div id="extra_price_c" class="exfm cl">
							Price:<input type="text" id="price" name="price" class="px pxs" onblur="extraCheck(2)" value="0" /> coins<span class="xg1">(at most 30 )</span>
							</div>
						</div>
					</div>
					<input type="hidden" id="classid" name="classid" value="{$classId}" />
					
					<div class="mtm mbm pnpost">
						<button type="submit" id="postsubmit" class="pn pnc" value="true" name="topicsubmit">
						<span>Post</span>
						</button>
					</div>
				
				</div>
			</div>
		</div>
	</div>
	</form>
	
	<script>
	
	var BROWSER = {};
	var USERAGENT = navigator.userAgent.toLowerCase();
	browserVersion({'ie':'msie','firefox':'','chrome':'','opera':'','safari':'','mozilla':'','webkit':'','maxthon':'','qq':'qqbrowser'});
	if(BROWSER.safari) {
		BROWSER.firefox = true;
	}
	BROWSER.opera = BROWSER.opera ? opera.version() : 0;

	function showLength(obj,checklen,maxlen){
	
		var v = obj.value, charlen = 0, maxlen = !maxlen ? 200 : maxlen, curlen = maxlen, len = strlen(v);
		for(var i = 0; i < v.length; i++) {
			if(v.charCodeAt(i) < 0 || v.charCodeAt(i) > 255) {
				curlen -= 2;
			}
		}
		if(curlen >= len) {
			document.getElementById("checklen").innerHTML = curlen - len;
		} else {
			obj.value = mb_cutstr(v, maxlen, true);
		}
	
	}
	
	function strlen(str) {
		return (BROWSER.ie && str.indexOf('\n') != -1) ? str.replace(/\r?\n/g, '_').length : str.length;
	}
	
	function mb_cutstr(str, maxlen, dot) {
		var len = 0;
		var ret = '';
		var dot = !dot ? '...' : '';
		maxlen = maxlen - dot.length;
		for(var i = 0; i < str.length; i++) {
			len += str.charCodeAt(i) < 0 || str.charCodeAt(i) > 255 ? 3 : 1;
			if(len > maxlen) {
				ret += dot;
				break;
			}
			ret += str.substr(i, 1);
		}
		return ret;
	}
	
	function extraCheck(len){
	
		strlen=document.getElementById('price').value.length;
		if(strlen>len){
			alert('at most 30');
			document.getElementById('price').value=0;
		}else{
		
			if(document.getElementById('price').value>30){
			
				alert('at most 30');
				document.getElementById('price').value=30;
			
			}
		
		}
	
	}
	</script>
</div>
<!--LIST end-->
{% endblock %}
<!--FOOT start-->
<!--{include footer.html}-->
<!--FOOT end-->
</body>
</html>

App/templates/foreground/close.html
<!--{include header.html}-->
<!--TOP start-->
<!--{include top.html}-->
<!--TOP end-->

<!--HEAD start-->
<!--{include head.html}-->
<!--HEAD end-->

<!--close START-->

	<!--{if empty($_COOKIE['uid'])}-->
		<div class="nfl" id="main_message">
			<div class="f_c altw">
				<div id="messagetext" class="alert_info">
					<p><!--{if empty($notice)}-->网站关闭<!--{else}-->{$notice}<!--{/if}--></p>
				</div>
				<div id="messagelogin"></div>
				
				<div id="main_messaqge_LAPpm">
				<div id="layer_login_LAPpm">
				<h3 class="flb">
				<em id="returnmessage_LAPpm">
				用户登录</em>
				<span></span>
				</h3>
				<form method="post" autocomplete="off" name="login" id="loginform_LAPpm" class="cl" action="login.php">
				<div class="c cl">
				<div class="rfm">
				<table>
				<tr>
				<th><label for="username_LAPpm">用户名:</label></th>
				<td><input type="text" name="username" id="username_LAPpm" autocomplete="off" size="30" class="px p_fre" /></td>
				<td class="tipcol"><a href="reg.php">立即注册</a></td>
				</tr>
				</table>
				</div>
				<div class="rfm">
				<table>
				<tr>
				<th><label for="password3_LAPpm">密码:</label></th>
				<td><input type="password" id="password3_LAPpm" name="password" size="30" class="px p_fre" /></td>
				<td class="tipcol"><a href="getpass.php" title="找回密码">找回密码</a></td>
				</tr>
				</table>
				</div>
				<div class="rfm">
				<table>
				<tr>
				<th>安全提问:</th>
				<td><select id="loginquestionid_LAPpm" width="213" name="questionid">
				<option value="0">安全提问(未设置请忽略)</option>
				<option value="1">母亲的名字</option>
				<option value="2">爷爷的名字</option>
				<option value="3">父亲出生的城市</option>
				<option value="4">你其中一位老师的名字</option>
				<option value="5">你个人计算机的型号</option>
				<option value="6">你最喜欢的餐馆名称</option>
				<option value="7">驾驶执照最后四位数字</option>
				</select></td>
				</tr>
				</table>
				</div>
				<div class="rfm" id="loginanswer_row_LAPpm">
				<table>
				<tr>
				<th>答案:</th>
				<td><input type="text" name="answer" id="loginanswer_LAPpm" autocomplete="off" size="30" class="px p_fre" /></td>
				</tr>
				</table>
				</div>
				
				
				<div class="rfm  bw0">
				<table>
				<tr>
				<th></th>
				<td><label for="cookietime_LAPpm"><input type="checkbox" class="pc" name="cookietime" id="cookietime_LAPpm" tabindex="1" value="true"  />自动登录</label></td>
				</tr>
				</table>
				</div>
				
				<div class="rfm mbw bw0">
				<table width="100%">
				<tr>
				<th>&nbsp;</th>
				<td>
				<button class="pn pnc" type="submit" name="loginsubmit" value="true" tabindex="1"><strong>登录</strong></button>
				</td>
				<td>
				</td>
				</tr>
				</table>
				</div>
				
				</div>
				</form>
				</div>
				</div>
				
		
			</div>
		</div>
	<!--{else}-->
		<div id="wp" class="wp">
			<div id="ct" class="wp cl w">
				<div class="nfl">
					<div class="f_c altw">
						<div id="messagetext" class="alert_error">
						<p>抱歉，本站点暂时关闭，<br />详情请 <a href="mailto:ccgy_yhsong@126.com">联系管理员</a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	<!--{/if}-->

<!--close END-->

<!--FOOT start-->
<!--{include footer.html}-->
<!--FOOT end-->
</body>
</html>

App/templates/foreground/footer.html
<div id="ft" class="wp cl">
	<div id="flk" class="y">
		<p>
		<a href="#" >{$web_icp}</a><span class="pipe">|</span><strong><a href="{$web_url}" target="_blank">{$web_btm}</a></strong>
		</p>
		<p class="xs0">
			Time Now Is: ${date('m-d H:i')}
		</p>
	</div>
	<div id="frt">
		<p>Powered by <strong><a href="{$web_url}" target="_blank">{$web_btm}</a></strong> <em>V2</em></p>
		<p class="xs0">&copy; ${date('Y')} <a href="{$web_url}" target="_blank">{$web_btm} Inc.</a></p>
	</div>
</div>

App/templates/foreground/header.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>{$title}</title>
	<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='foreground/css/style.css')}}" />
	<!--{if $thispage=="index.php"}-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='foreground/css/index.css')}}" />
	<!--{elseif $thispage=='list.php'}-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='foreground/css/list.css')}}" />
	<!--{elseif $thispage=='detail.php'}-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='foreground/css/view.css')}}" />
	<!--{elseif $thispage=='user.php'}-->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='foreground/css/home.css')}}" />
	<!--{/if}-->
</head>

<body>

App/templates/foreground/list.html
<!--{include header.html}-->
<!--TOP start-->
<!--{include top.html}-->
<!--TOP end-->

<!--HEAD start-->
<!--{include head.html}-->
<!--HEAD end-->


{% extends "foreground/base.html" %}
{% block content %}
<!--LIST start-->
<div id="wp" class="wp">
	<div id="pt" class="bm cl">
			<div class="z">
			<a href="./" class="nvhm" title="{$title}">{$title}</a><em>&raquo;</em><a href="{{ url_for("bbs.bbs_index") }}">Forum</a><em>&raquo;</em><a href="/{{first_layer_cid}}">{{ first_layer_name }}</a><em>&raquo;</em><a href="{{url_for('bbs.list_category', cid=cid, page=1) }}">{{other_layer_name}}</a>
			</div>
	</div>
	<div class="boardnav">
		<div id="ct" class="wp cl" style="margin-left:145px">
			<div id="sd_bdl" class="bdl" style="width:130px;margin-left:-145px">
				<div class="tbn" id="forumleftside"><h2 class="bdl_h">Sections</h2>
					<!--{loop $LTmenu $inde $bk}-->
                    {% for category in first_layer_category %}
					<dl class="a" id="lf_{$bk['cid']}">
						<dt><a href="javascript:;" title="{{category.classname}}">{{category.classname}}</a></dt>
						<!--{loop $LTsMenu $key $val}-->
                        {% for other in other_layer_category %}
                            {% if other.parentid == category.cid %}
						<!--{if $val['parentid']==$bk['cid']}-->
{#						<dd <!--{if $val['cid']==$OnCid}-->class="bdl_a"<!--{/if}-->>#}
						<a href="{{url_for('bbs.list_category', cid=other.cid, page=1)}}" title="{{other.classname}}"> {{other.classname}} </a><br>
						</dd>
						<!--{/if}-->
                            {% endif %}
						<!--{/loop}-->
                        {% endfor %}
					</dl>
					<!--{/loop}-->
                    {% endfor %}
				</div>
			</div>
			
			<div class="mn">
			
				<div class="bm bml pbn">
					<div class="bm_h cl">
					<h1 class="xs2">
					<a href="">{{other_layer_name}}</a>
					<span class="xs1 xw0 i">Today: <strong class="xi1">{{ post_num }}</strong><span class="pipe">|</span>Subjects: <strong class="xi1">{{post_num}}</strong></span></h1>
					</div>
					<!--{if !empty($compere)}-->
					<div class="bm_c cl pbn">
						
						<div>
							Compere: <span class="xi2">{{compere_name}}</span>
						</div>
						
					</div>
					<!--{/if}-->
				</div>
				
				<div id="pgt" class="bm bw0 pgs cl">
				<span class="pgb y"  ><a href="{{ url_for("bbs.bbs_index") }}">Return</a></span>
				<a href="{{ url_for('bbs.publish_post', cid=classid) }}" id="newspecial" title="New post"><img src="{{ url_for('static', filename = "foreground/images/pn_post.png") }}" alt="New post" /></a></div>
				
				<div id="threadlist" class="tl bm bmw">
				<div class="th">
				<table cellspacing="0" cellpadding="0">
				<tr>
				<th colspan="2">
				<div class="tf">
				Filter:
				<a href="" class="xi2">All</a><span class="pipe">|</span><a href="" class="xi2">Essence</a></div>
				</th>
				<td class="by">Author</td>
				<td class="num">Reply/View</td>
				<td class="by">Last reply</td>
				</tr>
				</table>
				</div>
				<div class="bm_c">
				<form method="post" autocomplete="off" name="moderate" id="moderate" action="">
				<table summary="forum_2" id="forum_2" cellspacing="0" cellpadding="0">
					{% for post in posts %}

						<tr>
							<td class="icn">
							<a href="{{ url_for('bbs.list_detail', postid=post.id, page=1) }}" title="{{ post.title }}"><img src="{{ url_for('static', filename='foreground/images/folder_common.gif') }}" /></a>
							</td>
							<th class="">
							 <a href="{{ url_for('bbs.list_detail', postid=post.id, page=1) }}" class="xst"  >{{ post.title }}</a>
							 {% if post.rate > 0 %}
							 - [Price <span class="xw1">{{post.rate}}</span> coins]
							 {% endif %}
							 {% if post.elite == 1 %}
							 <img src="{{ url_for('static', filename='foreground/images/digest_1.gif') }}" align="absmiddle" alt="digest" title="Essence" />
							 {% endif %}
{#							 <!--{if $val['addtime']>$newt}-->#}
{#							 <a href="" class="xi1">New</a>#}
{#							 <!--{/if}-->#}
							</th>
							<td class="by">
							<cite>Author: {{post.authorid}}</cite>
							<em><span class="xi1">{{ post.addtime }}</span></em>
							</td>
							<td class="num"><a href="" class="xi2">{{post.replycount}}</a><em>{{post.hits}}</em></td>
							<td class="by">
                                {% if reply_dict[post.id][0] %}
							    Author: {{ reply_dict[post.id][0] }}
                                {% endif %}
                                <br>
                                {{ reply_dict[post.id][1] }}
							</td>
						</tr>

					{% endfor %}
				</table>
				</form>
				</div>
				</div>
				
				<div class="bm bw0 pgs cl">
				<span  class="pgb y"><a href="{{ url_for("bbs.bbs_index") }}">Return</a></span>
				<a href="{{ url_for('bbs.publish_post', cid=classid) }}" id="newspecialtmp" title="New post"><img src="{{ url_for('static', filename = "foreground/images/pn_post.png") }}" alt="New post" /></a></div>
				<div style="width:800px; margin:0 auto; padding:10px 0px; text-align:right">
                    <a href="{{ url_for('bbs.list_category',cid=classid ,page=1) }}">Index</a>
                    {% if data["pre"] %}
                    <a href="{{ url_for('bbs.list_category',cid=classid ,page=data["pre"]) }}">Prev</a>
{#                    {% else %}#}
{#                    <a>Prev</a>#}
                    {% endif %}
                    {% if data["next"] %}
                    <a href="{{ url_for('bbs.list_category',cid=classid ,page=data["next"]) }}">Next</a>
                    {% endif %}

                    <a href="{{ url_for('bbs.list_category',cid=classid ,page=data["pages"]) }}">End</a>
                    | Total <span>{{ data["total"] }}</span> records |  show <span>{{ data['per_page'] }}</span> records per page |  <span>1-{{ length }}</span> record on this page  |  Page<span>{{ data['current'] }}/{{ data['pages'] }}</span>
				</div>
			</div>
		</div>
	</div>
</div>
<!--LIST end-->
{% endblock %}
<!--FOOT start-->
<!--{include footer.html}-->
<!--FOOT end-->
</body>
</html>

App/templates/foreground/notice_fail.html
<!--{include header.html}-->
<!--TOP start-->
<!--{include top.html}-->
<!--TOP end-->

<!--HEAD start-->
<!--{include head.html}-->
<!--HEAD end-->
{% extends "foreground/base.html" %}
{% block content %}
<!--NOTICE START-->
<div id="wp" class="wp">
	<div id="ct" class="wp cl w">
		<div class="nfl">
			<div class="f_c altw">
				<div id="messagetext" class="{$style}">
				<p>{{message}}<br />
				<script type="text/javascript" reload="1">setTimeout("location.href='{{ url_for('bbs.bbs_index') }}';", 3000);</script></p>
				<p class="alert_btnleft"><a href="{{ url_for('bbs.bbs_index') }}">If your browser does not redirect automatically, please click this link.</a></p>
				</div>
			</div>
		</div>
	</div>
</div>
<!--NOTICE END-->

<!--FOOT start-->
<!--{include footer.html}-->
<!--FOOT end-->
{% endblock %}
</body>
</html>